version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=assignment_app_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    volumes:
      - /data/mysql
  assignment-image:
    image: assignment-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 9221:9221
    volumes:
      - /data/assignment